name: Build Release Images

on:
  push:
    branches:
      - main

env:
  BUILD_VERSION: v2.3.0

jobs:
  build:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cn-qingdao.aliyuncs.com
          username: ${{ secrets.REGISTRY_USER_ALIYUN }}
          password: ${{ secrets.REGISTRY_PASSWORD_ALIYUN }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Cross Build
        run: |
          VERSION=${{ env.BUILD_VERSION }} bash ./.beagle/build.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push images for amd64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/awecloud-gateway:forward-auth-${{ env.BUILD_VERSION }}-amd64
          build-args: |
            BASE=registry.cn-qingdao.aliyuncs.com/wod/alpine:3
            VERSION=${{ env.BUILD_VERSION }}
            TARGETOS=linux
            TARGETARCH=amd64
          provenance: false
          sbom: false

      - name: Build and push images for arm64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: .beagle/dockerfile
          push: true
          platforms: linux/arm64
          tags: |
            registry.cn-qingdao.aliyuncs.com/wod/awecloud-gateway:forward-auth-${{ env.BUILD_VERSION }}-arm64
          build-args: |
            BASE=registry.cn-qingdao.aliyuncs.com/wod/alpine:3
            VERSION=${{ env.BUILD_VERSION }}
            TARGETOS=linux
            TARGETARCH=arm64
          provenance: false
          sbom: false

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create registry.cn-qingdao.aliyuncs.com/wod/awecloud-gateway:forward-auth-${{ env.BUILD_VERSION }} \
            registry.cn-qingdao.aliyuncs.com/wod/awecloud-gateway:forward-auth-${{ env.BUILD_VERSION }}-amd64 \
            registry.cn-qingdao.aliyuncs.com/wod/awecloud-gateway:forward-auth-${{ env.BUILD_VERSION }}-arm64
          docker manifest push registry.cn-qingdao.aliyuncs.com/wod/awecloud-gateway:forward-auth-${{ env.BUILD_VERSION }}
